### ISSUE TITLE
payload values out of date

### ISSUE THREAD

**Issue by draogn** [dawoudt/JustWatchAPI#11]
Was doing some debugging and noticed there's been some change in the api payload.

Payload from website clicking on cinema:

```json
{
    "age_certifications": null,
    "content_types": null,
    "genres": null,
    "languages": null,
    "max_price": null,
    "min_price": null,
    "monetization_types": ["cinema"],
    "nationwide_cinema_releases_only": true,
    "page": 1,
    "page_size": 10,
    "presentation_types": ["hd", "canvas"],
    "providers": null,
    "release_year_from": null,
    "release_year_until": null,
    "scoring_filter_types": null,
    "timeline_type": null
}
```
age_certifications and timeline_type are available.
looks like cinema_release may have been replaced by monetization_type = cinema with an additional option for nationwide_cinema_releases_only.

I don't have anything set up to look at cinema so don't know if / when this changed

**Comment by dawoudt** [comment]
Hmm what a confusing field. Haven’t seen it myself either. Whats returned when the field is set to cinema? If you feel that its something we should handle than you can hack up an implementation and ill give it an eyes over. 

Also I appreciate the time and effort you’ve put in for handling issues etc. Good job!

**Comment by draogn** [comment]
I've had a dig and added a couple more options in a branch.  Once I've updated the docs I'll add a pull request.
The cinema_release option doesn't seem to do anything.  Setting monetization_types to cinema does give back what's on at cinemas in the country and a reduced list is returned if nationwide_cinema_releases_only is set to true.

Here's the output from some testing.  As I've noted it needs something else to be able to handle distances.


## Justwatch  - cinema listings


Import the justwatch module


```python
from justwatch import JustWatch

```

Set a reference to the country



```python
just_watch = JustWatch(country='GB')
```

get reference to cinema release of tomb raider


```python
results = just_watch.search_for_item(query='Tomb Raider',
                                     monetization_types=["cinema"],
                                     nationwide_cinema_releases_only=False,
                                     page_size=500)['items'][0]
```


```python
print(results)
```

    {'id': 244150, 'title': 'Tomb Raider', 'full_path': '/uk/movie/tomb-raider', 'full_paths': {'MOVIE_DETAIL_OVERVIEW': '/uk/movie/tomb-raider'}, 'poster': '/poster/48688906/{profile}', 'short_description': 'Lara Croft, the fiercely independent daughter of a missing adventurer, must push herself beyond her limits when she finds herself on the island where her father disappeared.', 'original_release_year': 2018, 'tmdb_popularity': 244.226352, 'object_type': 'movie', 'original_title': 'Tomb Raider', 'localized_release_date': '2018-03-16', 'offers': [{'monetization_type': 'cinema', 'provider_id': 104, 'urls': {'standard_web': '29308'}, 'subtitle_languages': [], 'audio_languages': [], 'presentation_type': 'canvas', 'date_created_provider_id': '2018-01-04_104', 'date_created': '2018-01-04', 'country': 'GB'}], 'scoring': [{'provider_type': 'imdb:score', 'value': 7.5}, {'provider_type': 'tmdb:popularity', 'value': 244.226352}, {'provider_type': 'tomato:rating', 'value': 3}, {'provider_type': 'tomato:meter', 'value': 50}, {'provider_type': 'tmdb:id', 'value': 338970}, {'provider_type': 'tomato_userrating:meter', 'value': 65}, {'provider_type': 'tmdb:score', 'value': 6.2}, {'provider_type': 'tomato:id', 'value': 771442411}], 'original_language': 'en', 'runtime': 120, 'cinema_release_date': '2018-03-16', 'cinema_release_week': '2018_11', 'is_nationwide_cinema_release_date': True, 'age_certification': '12A'}


pull out the id


```python
this_title_id = results['id']
print(this_title_id)

```

    244150


now call to find details of the cinema times.  This is the coordinates if you set your location to London, UK


```python
cinema_times = just_watch.get_cinema_times(title_id=this_title_id,
                                           date='2018-03-24',
                                           latitude=51.5287718,
                                           longitude=-0.2416809,
                                           radius=20000)
```

check how many entries we got back and display the first 2.


```python
print(len(cinema_times))
print(cinema_times[0])
print(cinema_times[1])
```

    176
    {'id': 1498743160, 'movie_id': 244150, 'cinema_id': 29, 'audio_language': 'en', 'subtitle_language': None, 'local_start_at': '2018-03-24T10:20:00', 'auditorium': None, 'is_3d': False, 'booking_type': 'external', 'booking_url': 'https://sutton.empirecinemas.co.uk/?p=tickets&perfCode=7358'}
    {'id': 1498743188, 'movie_id': 244150, 'cinema_id': 29, 'audio_language': 'en', 'subtitle_language': None, 'local_start_at': '2018-03-24T21:30:00', 'auditorium': None, 'is_3d': False, 'booking_type': 'external', 'booking_url': None}


note from initial observation the booking_url isn't always populated



Now get back details of all the cinemas themselves.
The call takes latitute, longitude and radius - leave them blank and the values in the call to get_cinema_times are reused



```python
cinema_details = just_watch.get_cinema_details()
```

display the number of matches and find the details for cinema id 29


```python
print(len(cinema_details))
for cinema in cinema_details:
    if cinema['id'] == 29:
        print(cinema)
```

    112
    {'id': 29, 'full_path': '', 'cinema_chain_id': 5, 'name': 'Empire - Sutton', 'country': 'GB', 'latitude': 51.3645841, 'longitude': -0.1954462, 'address': {'city': 'Sutton', 'street': 'Saint Nicholas Way'}, 'contact': {'email': '', 'website': 'http://www.empirecinemas.co.uk/', 'telephone': '0871 471 4714'}, 'booking_type': 'external', 'region_id': 0}


note the website displays the details in increasing distance from the centre.  The data returned doesn't come back in this order - distances would need to be calculated and results sorted.  There's some possible solutions here:
https://stackoverflow.com/questions/19412462/getting-distance-between-two-points-based-on-latitude-longitude
There's also a project for converting uk postcodes to co-ordinates here: https://github.com/e-dard/postcodes

Another point is the cinema_chain_id.  This looks like it may be available like providers and genres but I couldn't find a url to call.

**Comment by draogn** [comment]
And for completeness here's the jupyter notebook that produced that 
[cinema investigation.ipynb.zip](https://github.com/dawoudt/JustWatchAPI/files/1844568/cinema.investigation.ipynb.zip)

**Comment by draogn** [comment]
As I've been a bit lazy in finalising this one I'll sort it out once pull request #12 and issue #13 resolved

**Comment by draogn** [comment]
This is just about ready to go.  I've added another call to get the upcoming cinema details which was straightforward enough


```python
import justwatch
jw = justwatch.JustWatch(country='GB')
```


```python
showings = jw.get_upcoming_cinema(weeks_offset=0, nationwide_cinema_releases_only=True)
showings
```




    {'page': 0,
     'page_size': 2,
     'total_pages': 1,
     'total_results': 2,
     'items': [{'id': 370630,
       'title': 'Book Club',
       'full_path': '/uk/movie/book-club',
       'full_paths': {'MOVIE_DETAIL_OVERVIEW': '/uk/movie/book-club'},
       'poster': '/poster/52503278/{profile}',
       'original_release_year': 2018,
       'object_type': 'movie',
       'original_title': 'Book Club'},
      {'id': 370212,
       'title': 'Adrift',
       'full_path': '/uk/movie/adrift-2018',
       'full_paths': {'MOVIE_DETAIL_OVERVIEW': '/uk/movie/adrift-2018'},
       'poster': '/poster/49841661/{profile}',
       'original_release_year': 2018,
       'object_type': 'movie',
       'original_title': 'Adrift'}]}




```python
output_list = []
for i in range(-20, 20):
        showings = jw.get_upcoming_cinema(weeks_offset=i)
        output_list.append((i, showings['total_results']))

print(output_list)
```

    [(-20, 3), (-19, 4), (-18, 6), (-17, 5), (-16, 5), (-15, 7), (-14, 3), (-13, 4), (-12, 6), (-11, 5), (-10, 7), (-9, 7), (-8, 6), (-7, 5), (-6, 6), (-5, 1), (-4, 11), (-3, 3), (-2, 5), (-1, 6), (0, 2), (1, 2), (2, 3), (3, 2), (4, 6), (5, 5), (6, 3), (7, 3), (8, 2), (9, 3), (10, 6), (11, 5), (12, 4), (13, 5), (14, 4), (15, 3), (16, 1), (17, 4), (18, 0), (19, 0)]



```python
showings

```




    {'page': 0, 'page_size': 0, 'total_pages': 1, 'total_results': 0, 'items': []}

**Comment by draogn** [comment]
Couldn't work out what timeline_type was for, but did manage to get hold of the possible certificates



```python
import justwatch
jw = justwatch.JustWatch(country='GB')
```


```python
certs = jw.get_certifications()
for this_cert in certs:
    print(this_cert['technical_name'])
    
print(this_cert.keys())
```

    U
    PG
    12A
    12
    15
    18
    R18
    dict_keys(['id', 'technical_name', 'description', 'object_type', 'country', 'order', 'organization'])
