### ISSUE TITLE
"error": "EOF"

### ISSUE THREAD

**Issue by amitpatnaikse** [dawoudt/JustWatchAPI#7]
{
    "error": "EOF"
}

400 Bad request

URL : https://api.justwatch.com/titles/en_US/popular

Kindly reply ASAP

**Comment by draogn** [comment]
Could you post the code you are trying to run?

**Comment by amitpatnaikse** [comment]
Nop Sir ...It's working fine..Had firewall issue

**Comment by amitpatnaikse** [comment]
Hey Team,

I am running the code using java but getting only the 30 titles and tried
manually with POSTMAN which yields the same result.

RestAssured.baseURI="*https://api.justwatch.com/titles/en_US/popular
<https://api.justwatch.com/titles/en_US/popular>*";
RestAssured.useRelaxedHTTPSValidation();
String strJSON = "
{\"content_types\":null,\"presentation_types\":null,\"providers\":null,\"genres\":null,\"languages\":null,\"release_year_from\":null,\"release_year_until\":null,\"monetization_types\":null,\"min_price\":null,\"max_price\":null,\"scoring_filter_types\":null,\"cinema_release\":null,\"query\":null,\"page\":null,\"page_size\":null}";
RequestSpecification reqSpec=RestAssured.given();
reqSpec.header("User-Agent", "JustWatch Python client (
github.com/dawoudt/JustWatchAPI)");
reqSpec.header("Content-Type", "application/json");
reqSpec.body(strJSON);
Response resp=reqSpec.post();
System.out.println(resp.getStatusCode());
String body = resp.getBody().asString();
JSONStringValidator validator = new JSONStringValidator(body);
System.out.println(validator.isValidJson());
JSONObject parser = new JSONObject(body);
System.out.println(parser.get("total_results"));
String strItem = parser.get("items").toString();
JSONArray parsedObject = new JSONArray(strItem);
System.out.println("Array "+parsedObject.length());
for(int i=0;i<parsedObject.length();i++) {
JSONObject json = parsedObject.getJSONObject(i);
System.out.println(json.get("title"));
}

Output :

[image: Inline image 1]


Regards,
Amit

**Comment by draogn** [comment]
If you have a look at pull request #6 there's an example of how to get multiple pages back.  You can specify your page number (using the 'page' argument) and required page size ('page_size') in your request and the results return a page total ('total_pages').

**Comment by amitpatnaikse** [comment]
Thanks Guys for prompt reply

**Comment by amitpatnaikse** [comment]
Hi Team,

There are some info missing in the result like price , director and cast.
If we can get those information that will be very helpful.

[image: Inline image 1]

Thanks,
Amit

**Comment by draogn** [comment]
Price comes back in the call - have a look under the 'offers' key.  Anything with monetization_type of rent or buy will have a price under 'retail_price'

For cast etc. you'll need to do a second call based on the data you get back.
The data you're currently getting has an id key that you need to use.
You'll then need to do a get request to 
https://apis.justwatch.com/content/titles/movie/IDNUMBER/locale/{}_{}
where
IDNUMBER is the id from your first request and
{}_{} is your language settings as gets set in justwatchapi.py - e.g. en_GB

Something like this will get you what you're after
```
import requests
import json
req = requests.get('https://apis.justwatch.com/content/titles/movie/107744/locale/en_GB')
json_data = json.loads(req.text)

```

**Comment by amitpatnaikse** [comment]
Hi Team,

The genre info is missing in the get call
https://apis.justwatch.com/content/titles/movie/122337/locale/en_US

If we can get this it will be helpfull

Regards,
Amit

**Comment by amitpatnaikse** [comment]
Adding to the previous query:

I got this from API :

genre_ids":[1,10,3,2]

Where we can get the info like : Action | Adventure | Drama


-Thanks in Advance

**Comment by draogn** [comment]
If you reload a page with inspect / inspect element visible and look at Network / XHR you can find all this.
Looks like a call to https://apis.justwatch.com/content/genres/locale/<your_locale> gives you the genre mapping back.
All I did myself for a similar issue with the providers was put a mapping list in the code.

**Comment by amitpatnaikse** [comment]
Thanks Team for the help
Keep up the great work.

Cheers,
Amit

**Comment by amitpatnaikse** [comment]
Hi Team,

total_results = 61,638

I have given page = 1 and page_size=10000

In the result I am getting this response :

{
    "page": 1,
    "page_size": 10000,
    "total_pages": 0,
    "total_results": 61640,
    "items": [
        {
            "id": 122337,
            "title": "Zootopia",
            "full_path": "/us/movie/zootopia",
            "full_paths": {
                "MOVIE_DETAIL_OVERVIEW": "/us/movie/zootopia"
            },

As per my understanding the total_pages should be 6 or 7 because we are
receiving only 10k records out of 60k odd records.

Regards,
Amit

**Comment by amitpatnaikse** [comment]
Guys,

Can you reply this ASAP.
Because I am unable to move forward.

Thanks,
Amit

**Comment by draogn** [comment]
I don't think the api is designed to allow a scrape of their entire database.  What's the use case for getting 60k+ records?

**Comment by amitpatnaikse** [comment]
Hi Team,

Just exploring all the options.
It's a assignment that has been assigned to me by my instructor.
I have automated the same thing via selenium but there are lot off issue
with that.

Note : If the API can get 1400 records then what is the hitch of getting
62k records(Just curious)

Thanks for all the help.

Cheers,
Amit

**Comment by amitpatnaikse** [comment]
Team,

Waiting for the reply

Amit-
